In [2]:
import numpy as np


In [4]:
data = np.array([6,38,3,34,45,442,545,757])

In [5]:
data

array([  6,  38,   3,  34,  45, 442, 545, 757])

In [10]:
data1 =np.array([[6, 38,   3,  34,  45, 442, 545, 757],
                 [93,89,35,28,89,1,2,3]])

In [11]:
data1

array([[  6,  38,   3,  34,  45, 442, 545, 757],
       [ 93,  89,  35,  28,  89,   1,   2,   3]])

In [12]:
data.nbytes

64

In [13]:
data1.ndim

2

## diff method to create numpy array 

In [14]:
#1
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.arange(1,8,2)

array([1, 3, 5, 7])

In [20]:
np.linspace(1,3,8)

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        ])

In [21]:
data.shape

(8,)

In [22]:
data1.shape

(2, 8)

In [23]:
data.size

8

In [25]:
data.dtype

dtype('int64')

In [30]:

data2 = np.array([6, 38, 3, 34, 45, 442, 545, 757], dtype=np.float64)


In [31]:
data2.dtype

dtype('float64')

In [33]:
data2.astype(np.float32)

array([  6.,  38.,   3.,  34.,  45., 442., 545., 757.], dtype=float32)

In [34]:
a =data.flat[1:3].copy()

In [35]:
a

array([38,  3])

In [36]:
data>50

array([False, False, False, False, False,  True,  True,  True])

In [51]:
arr = np.array([
    [[1,2,3,4,5,6,7,8,9,10],
     [11,12,13,14,15,16,17,18,19,20]],

    [[21,22,23,24,25,26,27,28,29,30],
     [31,32,33,34,35,36,37,38,39,40]]
])


In [52]:
arr.ndim

3

In [53]:
arr.size

40

In [54]:
arr.shape

(2, 2, 10)

In [56]:
arr[:,:,2] =0

In [57]:
arr

array([[[ 1,  2,  0,  4,  5,  6,  7,  8,  9, 10],
        [11, 12,  0, 14, 15, 16, 17, 18, 19, 20]],

       [[21, 22,  0, 24, 25, 26, 27, 28, 29, 30],
        [31, 32,  0, 34, 35, 36, 37, 38, 39, 40]]])

In [58]:
arr.mean(axis =0)

array([[11., 12.,  0., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22.,  0., 24., 25., 26., 27., 28., 29., 30.]])

In [59]:
arr.sum(axis =0)

array([[22, 24,  0, 28, 30, 32, 34, 36, 38, 40],
       [42, 44,  0, 48, 50, 52, 54, 56, 58, 60]])

# pandas


In [3]:
import pandas as pd

In [6]:
s = pd.Series([1,2,3,4,56,7,8,9])

In [7]:
s

0     1
1     2
2     3
3     4
4    56
5     7
6     8
7     9
dtype: int64